services:
    postgres:
        container_name: sv-postgres
        image: postgres:16.2
        restart: always
        volumes:
            - sv-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: sv-db

volumes:
    sv-data:
