import type { EncryptedMessage, PollResponse } from '@sealed-vote/contracts';
export type PollPhase = 'registration' | 'key-generation' | 'voting' | 'tallying' | 'decryption' | 'complete';
export declare const derivePollPhase: (poll: PollResponse) => PollPhase;
export declare const canRegister: (poll: PollResponse) => boolean;
export declare const canClose: (poll: PollResponse, voterCount?: number) => boolean;
export declare const canSubmitPublicKeyShare: (poll: PollResponse) => boolean;
export declare const canVote: (poll: PollResponse) => boolean;
export declare const canSubmitDecryptionShares: (poll: PollResponse) => boolean;
export declare const computeGeometricMean: (results: number[], voterCount: number) => number[];
export declare const serializeVotes: (scores: Record<string, number>, choices: string[], commonPublicKey: bigint) => EncryptedMessage[];
export declare const createDecryptionSharesForTallies: (encryptedTallies: EncryptedMessage[], privateKey: bigint) => string[];
export declare const computeEncryptedTallies: (encryptedVotes: EncryptedMessage[][]) => EncryptedMessage[];
export declare const decryptTallies: (encryptedTallies: EncryptedMessage[], decryptionShares: string[][]) => number[];
