BEGIN;

DROP TABLE IF EXISTS decryption_shares;
DROP TABLE IF EXISTS encrypted_votes;
DROP TABLE IF EXISTS voters;
DROP TABLE IF EXISTS public_key_shares;
DROP TABLE IF EXISTS choices;
DROP TABLE IF EXISTS polls;

DROP EXTENSION IF EXISTS pgcrypto;

COMMIT;
